version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9.3
    working_directory: /go/src/github.com/project/repo
    steps:
      - setup_remote_docker:
          version: 17.11.0-ce
          docker_layer_caching: true
      - checkout
      - run:
          name: Build
          command: docker build -t soubaramos/v1.4:latest .
      - run:
          name: Tag to latest
          command: docker tag soubaramos/v1.4:latest $soubaramos/v1.4:$CIRCLE_TAG
      - run:
          name: Docker Login
          command: docker login -u soubaramos -p sou102606
      - run:
          name: Push image to registory
          command: docker push soubaramos/v1.4
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/